```{r}
library(tidyverse)
library(geosphere)
library(parallel)
```

```{r}
airbnb = read.csv('Airbnb_NYC_2019.csv')
airbnb = airbnb %>% select(-c(id, host_id, host_name, name, last_review))

subway = read.csv('nyc-transit-subway-entrance-and-exit-data.csv')
```

```{r}
bnb_locations = tibble(listing = airbnb$id,
                       along = airbnb$longitude,
                       alat = airbnb$latitude)

bnb_locations = distinct(bnb_locations, listing, .keep_all = TRUE)

subway_locations = tibble(station = subway$Station.Name,
                   slong = subway$Station.Longitude,
                   slat = subway$Station.Latitude)

subway_locations = distinct(subway_locations, station, .keep_all = TRUE)
```

###################### Sample for testing ############################
 
```{r}
bnb_test = bnb_locations %>% sample_n(5)
sub_test = subway_locations %>% sample_n(5)
```

```{r}
bnb_test[,2:3]
sub_test[,2:3]
distmatrix_test = distm(bnb_test[,2:3], sub_test[,2:3])
distmatrix_test

colnames(distmatrix_test) <- sub_test$station
rownames(distmatrix_test) <- bnb_test$listing
distmatrix_test
```

```{r}
apply(distmatrix_test, 1, function(x) getClosestStation(distmatrix_test, x)) %>% bind_rows()
```
#####################################################################

```{r}
distmatrix = distm(bnb_locations[,2:3], subway_locations[,2:3])
colnames(distmatrix) <- subway_locations$station
rownames(distmatrix) <- bnb_locations$listing
```


```{r}

getClosestStation = function(distmatrix, x){
  station = colnames(distmatrix)[which.min(x)]
  distance_miles = min(x)/1609.34
  tibble(station = station, miles = distance_miles)
}



airbnb_wdist = apply(distmatrix, 1, function(x) getClosestStation(distmatrix, x)) %>% bind_rows()

airbnb_wdist
```

```{r}
airbnb_all = cbind(airbnb, airbnb_wdist)
glimpse(airbnb_all)
```


```{r}

fit = lm(price ~ latitude + longitude, data = airbnb)
summary(fit)

```



```{r}
airbnb = read.csv('Airbnb_NYC_2019.csv')
airbnb = airbnb %>% mutate(
  islong = case_when(
    availability_365 > 150 ~ 1,
    TRUE ~ 0
  )
)

table(airbnb$islong)
logfit = lm()
```
