```{r}
library(randomForest)
library(tidyverse)
library(geosphere)
library(parallel)
library(corrgram)
library(corrplot)
library(mltools)
library(data.table)
library(glmnet)
library(boot) #for cross validation

#Visualization
library(tidyverse)
library(sf)
library(leaflet)
library(htmlwidgets)
library(webshot)
library(viridis)
library(highcharter)
library(usethis)
library(devtools)
#install_github("wch/webshot")
#webshot::install_phantomjs()
library(webshot)
library(mapview)
```

```{r}
airbnb = read.csv('Airbnb_NYC_2019.csv')
airbnb_all = read.csv('airbnb_wdistances.csv')
nysubways = read.csv('nyc-transit-subway-entrance-and-exit-data.csv')
ethnames = read.csv('EthnicityPredictions.csv')
# Checking for NAs in all columns

sapply(airbnb_all, function(x) sum(is.na(x)))

#

# Replacing NAs in reviews_per_month with 0

airbnb_all = airbnb_all %>% mutate(reviews_per_month = replace_na(reviews_per_month, 0),
                                   host_name = as.character(host_name),
                                   ethnicity = as.character(ethnames$race))
table(airbnb_all$ethnicity)
head(airbnb_all %>% select(host_name,ethnicity))
head(ethnames %>% select(1:2))
```

```{r}
summary(log(airbnb_all$price))



# Getting rid of rows with price = 0  (Does not help i analysis)

airbnb_all =(airbnb_all[(airbnb_all$price != 0), ])



# Now we get rid of the columns which have no bearing on predicting price

airbnb_all %>% glimpse()

min_nights_365 = airbnb_all %>% filter(minimum_nights <= 365)
min_nights_365 #48870 out of 48884

ggplot(min_nights_365,aes(x = minimum_nights)) + geom_histogram() + scale_x_continuous(breaks = seq(0,365, by = 40)) # most nights within 30 

min_nights_30 = airbnb_all %>% filter(minimum_nights <= 30) #48137

# (48870-48137)/48884 = 1.5% of the data has min_nights > 30. Hence we get rid of those rows


airbnb_model = airbnb_all %>% filter(minimum_nights <= 30)
```

# Airbnb new model
```{r}
airbnb_new_model = airbnb_model %>% filter(price <= 269)
```


#Preprocessing airbnb names
```{r}
dirt = c("ú","&","")

airbnb_all = airbnb_all %>% mutate(host_name_clean = case_when(
    grepl(" (And|Or|&) ", host_name) ~ gsub("(.+?)(And|Or|&).*", "\\1", host_name),
    grepl("(&|\\+|\\/)", host_name) ~ gsub("(.+?)(\\+).*", "\\1", host_name),
    grepl("ú",host_name) ~ gsub("ú","a",host_name),
    grepl("é",host_name) ~ gsub("é", "ae", host_name),
    TRUE ~ host_name
  ))

write.csv(airbnb_all, 'airbnb_all_ethn.csv')
#View(airbnb_all %>% select(host_name, host_name_clean))
#airbnb_all
```


#Airbnb data with price ranges
```{r}
airbnb_all_priceClasses = airbnb_all %>%
  mutate(price_class = case_when(
    price < 69 ~ "affordable",
    (price >= 69 & price < 106) ~ "medium",
    (price >= 106 & price < 175) ~ "expensive",
    (price >= 175) ~ "very_expensive",
    TRUE ~ "NA"
  )
)
#airbnb_all_priceClasses$price_class %>% table()
```

#Leaflet map of neighborhood groups + subway locations

```{r}
pal = colorFactor(palette = c("red","green","blue", "purple","yellow"), domain = airbnb_all$neighbourhood_group)

map_ng_subs = leaflet(data = airbnb_all) %>% 
  addProviderTiles(providers$CartoDB.DarkMatterNoLabels) %>% 
  addCircleMarkers(~longitude, ~latitude, color = ~pal(neighbourhood_group), weight = 1, radius = 1, fillOpacity = 0.1, opacity = 0.1,
                   label = paste("Name:", airbnb$name)) %>% 
  addLegend("bottomright", pal = pal, values = ~ neighbourhood_group,
            title = "Neighborhood groups", opacity = 1) %>%  addCircleMarkers(data = nysubways, ~ Station.Longitude, ~Station.Latitude, color = "orange", weight = 1, radius = 1, fillOpacity = 0.1, opacity = 1,
                   label = paste("Name:", nysubways$Station.Name))

mapshot(map_ng_subs, file = paste0(getwd(),"/NeighborhoodGroup_Subs_Map.png"))
```

#Leaflet map of subway locations

```{r}
#glimpse(nysubways)
#table(nysubways$Station.Name)

#pal = colorFactor(palette = c("red","green","blue", "purple","yellow"), domain = airbnb_all$neighbourhood_group)

map_subs = leaflet(data =nysubways) %>% 
  addProviderTiles(providers$CartoDB.DarkMatterNoLabels) %>% 
  addCircleMarkers(~ Station.Longitude, ~Station.Latitude, color = "orange", weight = 1, radius = 1, fillOpacity = 0.1, opacity = 0.1,
                   label = paste("Name:", nysubways$Station.Name))

mapshot(map_subs, file = paste0(getwd(),"/subway_map.png"))
```

#Leaflet map of price classes with subway locations

```{r}
#airbnb_all_priceClasses
pal = colorFactor(palette = c("green","yellow","orange","red"), domain = airbnb_all_priceClasses$price_class)

map_price_subs = leaflet(data = airbnb_all_priceClasses) %>% 
  addProviderTiles(providers$CartoDB.DarkMatterNoLabels) %>% 
  addCircleMarkers(~longitude, ~latitude, color = ~pal(price_class),
                   weight = 1,
                   radius = 1,
                   fillOpacity = 0.1,
                   opacity = 0.1,
                   label = paste(airbnb_all_priceClasses$price))%>% 
  addLegend("bottomright", pal = pal, values = ~ price_class,
            title = "Price ranges", opacity = 1) %>% addCircleMarkers(data = nysubways, ~ Station.Longitude, ~Station.Latitude, color = "white", weight = 1, radius = 1, fillOpacity = 0.1, opacity = 1,
                   label = paste("Name:", nysubways$Station.Name))
mapshot(map_price_subs, file = paste0(getwd(),"/Price_Subs_Map.png"))
```
```{r}
#map of room types

pal = colorFactor(palette = c("blue","yellow","red"), domain = airbnb_all$room_type)

map_roomtype = leaflet(data = airbnb_all) %>% 
  addProviderTiles(providers$CartoDB.DarkMatterNoLabels) %>% 
  addCircleMarkers(~longitude, ~latitude, color = ~pal(room_type),
                   weight = 1,
                   radius = 1,
                   fillOpacity = 0.1,
                   opacity = 0.1,
                   label = paste(airbnb_all$room_type))%>% 
  addLegend("bottomright", pal = pal, values = ~ room_type,
            title = "Price ranges", opacity = 1) %>% addCircleMarkers(data = nysubways, ~ Station.Longitude, ~Station.Latitude, color = "white", weight = 1, radius = 1, fillOpacity = 0.1, opacity = 1,
                   label = paste("Name:", nysubways$Station.Name))

mapshot(map_roomtype, file = paste0(getwd(),"/RoomType_Map.png"))
```


```{r}
length(table(airbnb_all$ethnicity))
pal = colorFactor(palette = rainbow(length(unique(airbnb_all$ethnicity))), domain = airbnb_all$ethnicity)

map_ethn = leaflet(data = airbnb_all) %>% 
  addProviderTiles(providers$CartoDB.DarkMatterNoLabels) %>% 
  addCircleMarkers(~longitude, ~latitude, color = ~pal(ethnicity),
                   weight = 1,
                   radius = 1,
                   fillOpacity = 0.1,
                   opacity = 0.1,
                   label = paste(airbnb_all$ethnicity))%>% 
  addLegend("bottomright", pal = pal, values = ~ ethnicity,
            title = "Ethnicities", opacity = 1)

mapshot(map_ethn, file = paste0(getwd(),"/Ethnicity_Map.png"))
```

```{r}
ggplot(data = airbnb_all, aes(x = factor(1), fill = ethnicity)) +
  geom_bar(width = 1) + coord_polar("y")
```
```{r}
reduced_ethn_df = airbnb_all %>% 
  filter(ethnicity %in% c("GreaterEuropean,British", "GreaterEuropean,EastEuropean", "GreaterAfrican,Africans","GreaterAfrican,Muslim"))

#unique(reduced_ethn_df$ethnicity)
```

```{r}
pal = colorFactor(palette = rainbow(length(unique(reduced_ethn_df$ethnicity))), domain = reduced_ethn_df$ethnicity)

map_redEthn = leaflet(data = reduced_ethn_df) %>% 
  addProviderTiles(providers$CartoDB.DarkMatterNoLabels) %>% 
  addCircleMarkers(~longitude, ~latitude, color = ~pal(ethnicity),
                   weight = 1,
                   radius = 1,
                   fillOpacity = 0.1,
                   opacity = 0.1,
                   label = paste(reduced_ethn_df$ethnicity))%>% 
  addLegend("bottomright", pal = pal, values = ~ ethnicity,
            title = "Ethnicities", opacity = 1)

mapshot(map_redEthn, file = paste0(getwd(),"/ReducedEthncity.png"))
```

```{r}
# short-rental, medium-rental, long-rental 
summary(airbnb_all$availability_365)

airbnb_all = airbnb_all %>%
  mutate(availability_class = case_when(
    availability_365 <= 30 ~ "short",
    (availability_365 > 30 & availability_365 <= 180) ~ "medium",
    (availability_365 > 180) ~ "long",
    TRUE ~ ""
  )
)
```

```{r}

pal = colorFactor(palette = c("green","yellow","red"), domain = airbnb_all$availability_class)

map_availtypes = leaflet(data = airbnb_all) %>% 
  addProviderTiles(providers$CartoDB.DarkMatterNoLabels) %>% 
  addCircleMarkers(~longitude, ~latitude, color = ~pal(availability_class),
                   weight = 1,
                   radius = 1,
                   fillOpacity = 0.1,
                   opacity = 0.1,
                   label = paste(airbnb_all$availability_class))%>% 
  addLegend("bottomright", pal = pal, values = ~ availability_class,
            title = "Availability Types", opacity = 1)

mapshot(map_availtypes, file = paste0(getwd(),"/Availability_Map.png"))
```

```{r}
summary(airbnb_all$miles)
hist(airbnb_all$miles)
pal = colorNumeric(palette = "Blues", domain = airbnb_all$miles)

leaflet(data = airbnb_all) %>% 
  addProviderTiles(providers$CartoDB.DarkMatterNoLabels) %>% 
  addCircleMarkers(~longitude, ~latitude, color = ~pal(airbnb_all$miles),
                   weight = 1,
                   radius = 1,
                   fillOpacity = 0.1,
                   opacity = 0.1,
                   label = paste(airbnb_all$miles))%>% 
  addLegend("bottomright", pal = pal, values = ~ miles,
            title = "Availability Types", opacity = 1)
```