```{r}
library(tidyverse)
#install.packages("ggthemes")
#install.packages("ggExtra")
#install.packages("glmnet")
#install.packages("kableExtra")
#install.packages("leaflet")
#install.packages("RColorBrewer")
#install.packages("plotly")
library(ggthemes)
library(GGally)
library(ggExtra)
library(caret)
library(glmnet)
library(corrplot)
library(leaflet)
library(kableExtra)
library(RColorBrewer)
library(plotly)
#install.packages("ggmap")
library(ggmap)
th <- theme_fivethirtyeight() + theme(axis.title = element_text(), axis.title.x = element_text()) # global theme for ggplot2 objects
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rlang)
library(devtools)
#library(wru)
#outdated
#install_github("cdcrabtree/nomine")
library(nomine)
```

```{r}
airbnb = read.csv("Airbnb_NYC_2019.csv")
airbnb = airbnb %>% mutate(host_name = as.character(host_name))
names(airbnb)
View(airbnb)
```

# Data Exploration

```{r}
sum(is.na(airbnb$name))
colSums(is.na(airbnb)) %>% as.data.frame()
```
# Deal with NAs

```{r}
airbnb = airbnb %>% mutate(reviews_per_month = replace_na(airbnb$reviews_per_month, 0))
#works
#sum(is.na(test))
```

#Deal with listing ames
```{r}
head(airbnb$name)
``` 

#Deal with name of person
```{r}
head(airbnb$host_name,10)
# ú
dirt = c("ú","&","")
#names with &
needfix = airbnb[grep("&", airbnb$host_name),]
#https://stackoverflow.com/questions/33683862/first-entry-from-string-split
needfix$host_name = sapply(strsplit(needfix$host_name," &"),`[`,1)
needfix$host_name = sapply(strsplit(needfix$host_name,"&"),`[`,1)
needfix$host_name = sapply(strsplit(needfix$host_name,","),`[`,1)
head(needfix)
test = airbnb %>% 
  mutate(host_name = case_when(
      grepl("&",host_name) ~ strsplit(host_name," &")[[1]][1],
      TRUE ~ .
    )
  )
```



```{r}
library(ggplot2)
#removed listings beyond the price of 1000
airbnb_red = airbnb[airbnb$price < 1000,]
ggplot(airbnb_red, aes(x = price, fill = neighbourhood_group)) + geom_histogram() + facet_grid(neighbourhood_group~.)
sum(airbnb$price > 1000)
nrow(airbnb)
```



```{r}
top10_neighbourhood_bylistings = airbnb %>% 
  group_by(neighbourhood) %>% 
  tally() %>% 
  arrange(desc(n)) %>% 
  head(10)
airbnb_toplist = airbnb %>% filter(neighbourhood %in% top10_neighbourhood_bylistings$neighbourhood)
#https://stackoverflow.com/questions/16961921/plot-data-in-descending-order-as-appears-in-data-frame
ggplot(top10_neighbourhood_bylistings, aes(x = reorder(neighbourhood, n), y = n)) + geom_bar(stat = "identity", fill = "steelblue") + coord_flip() + xlab("Neighbourhood") + ylab("Number of listings") + theme_minimal() + geom_text(aes(label=n), vjust=0.3, hjust = 1.2, size=3.5,color = "white") + ggtitle("Top 10 Neighbourhoods by Listing")

```



```{r}
ggplot(airbnb_red, aes(x = price, fill = neighbourhood_group)) + geom_histogram() + facet_grid(neighbourhood_group~.)
```




```{r}
roomtype_byneighbourhood <- airbnb %>% group_by(neighbourhood_group,room_type) %>% tally()
#roomtype_byneighbourhood

ggplot(roomtype_byneighbourhood, aes(fill=room_type, y=n, x=neighbourhood_group)) + 
    geom_bar(position="dodge", stat="identity") + ggtitle("Room Type for each Neighbourhood Group") + xlab("Neighbourhood Group") + ylab("Number of Listings")
```




```{r}

# Distribution of log Price

ggplot(airbnb, aes(price)) +
  geom_histogram(bins = 30, aes(y = ..density..), fill = "blue") + 
  geom_density(alpha = 0.2, fill = "white") +
  ggtitle("Transformed distribution of price (log(price))") +
  geom_vline(xintercept = round(mean(airbnb$price), 2), size = 2, linetype = 1) +
  scale_x_log10() +  geom_vline(xintercept = round(median(airbnb$price), 2), size = 2, linetype = 2) +
  annotate("text", x = 1800, y = 0.75,label = paste("Mean price = ", "$",paste0(round(mean(airbnb$price), 2))),
           color =  "red", size = 6)
```


```{r}

ggmap::register_google(key = "AIzaSyDskGqnnm9FoVOGXWKbxh88vzF8k89UAjY")

p <- ggmap(get_googlemap(center = c(lon = -122.335167, lat = 47.608013),
                    zoom = 11, scale = 2,
                    maptype ='terrain',
                    color = 'color'))
p + geom_point(aes(x = Longitude, y = Latitude,  colour = Initial.Type.Group), size = 0.5) + 
  theme(legend.position="bottom")

get_local_spot <-  get_map("Durham North Carolina", maptype = "roadmap", zoom = 17) 
ggmap(get_local_spot)

```


```{r}
geocode("New York City")
map <- get_googlemap(center = c(-74, 40), zoom = 10)

ggmap(map) + geom_point(data = airbnb, aes(x = longitude, y = latitude))


p <- ggmap(get_googlemap("New York City",
                    zoom = 15, scale = 2,
                    maptype ='terrain',
                    color = 'color'))
```


```{r}
p + geom_point(aes(x = longitude, y = latitude), data = airbnb, size = 0.5,fill=airbnb$price) + 
  theme(legend.position="bottom")


```


```{r}
library(maps)
library(mapproj)
USA <- map_data("world") %>% filter(region=="USA")
ggplot() +
  geom_polygon(data = USA, aes(x=long, y = lat, group = group), fill="grey", alpha=0.3) +
  geom_point( data=airbnb, aes(x=longitude, y=latitude)) +
  theme_void() + ylim(50,59) + coord_map() 
 
```


```{r}

library(reticulate)
use_python('C:/Users/Falak/AppData/Local/Continuum/anaconda3/')

```

```{python}
import numpy as np
import pandas as pd
import seaborn as sns
import plotnine
from plotnine import *
import matplotlib as mpl
import matplotlib.pyplot as plt
import gmaps

```

```{r}
conda_install('re-reticulate', packages = 'numpy')
```

```{r}
#library(viridis)
ggplot(airbnb,aes(x = longitude, y = latitude, color = neighbourhood_group)) + geom_point()+scale_color_brewer(palette = "Dark2")
```

```{r}
  ggplot(airbnb,aes(x = price, fill = neighbourhood_group)) +
  geom_histogram(bins = 40) +
  scale_x_log10() + 
  ggtitle("Summary of price distributions") +
  facet_wrap(~room_type + neighbourhood_group)
```

